### ISSUE TITLE
can not install webtorrent-hybrid

### ISSUE THREAD

**Issue by makelove** [webtorrent/webtorrent-hybrid#105]
**What version of this package are you using?**
latest

**What operating system, Node.js, and npm version?**
macos  10.14.5 
node v12.4.0
npm 6.9.0

**What happened?**
npm install webtorrent-hybrid -g
npm ERR! code ETARGET
npm ERR! notarget No matching version found for wrtc@^0.4.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'webtorrent-hybrid'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/play/.npm/_logs/2019-08-19T03_23_58_329Z-debug.log

**Comment by feross** [comment]
This error doesn't really make sense to me. You can see that `wrtc` version 0.4.1 clearly exists: https://www.npmjs.com/package/wrtc/v/0.4.1

Perhaps you should kill your npm cache with `npm cache clean && sudo npm cache clean` and then try again?

**Comment by makelove** [comment]
is the same

**Comment by makelove** [comment]
/Users/play/.npm/_logs/2019-08-19T03_23_58_329Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/12.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'webtorrent-hybrid',
1 verbose cli   '-g'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.4.0
4 verbose npm-session f5644ada81df0117
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npm.taobao.org/webtorrent-hybrid 216ms (from cache)
8 silly pacote tag manifest for webtorrent-hybrid@latest fetched in 243ms
9 timing stage:loadCurrentTree Completed in 283ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule webtorrent-hybrid@4.0.0 checking installable status
17 http fetch GET 304 https://registry.npm.taobao.org/webtorrent-cli 119ms (from cache)
18 silly pacote range manifest for webtorrent-cli@^3.0.0 fetched in 122ms
19 silly resolveWithNewModule webtorrent-cli@3.0.0 checking installable status
20 http fetch GET 304 https://registry.npm.taobao.org/wrtc 167ms (from cache)
21 silly registry:manifest no matching version for wrtc@^0.4.1 in the cache. Forcing revalidation.
22 http fetch GET 304 https://registry.npm.taobao.org/create-torrent 176ms (from cache)
23 silly pacote range manifest for create-torrent@^4.0.0 fetched in 182ms
24 silly resolveWithNewModule create-torrent@4.3.0 checking installable status
25 http fetch GET 304 https://registry.npm.taobao.org/webtorrent 264ms (from cache)
26 silly pacote range manifest for webtorrent@^0.x fetched in 288ms
27 silly resolveWithNewModule webtorrent@0.107.4 checking installable status
28 http fetch GET 200 https://registry.npm.taobao.org/wrtc 126ms
29 silly fetchPackageMetaData error for wrtc@^0.4.1 No matching version found for wrtc@^0.4.1
30 timing stage:rollbackFailedOptional Completed in 0ms
31 timing stage:runTopLevelLifecycles Completed in 604ms
32 verbose type range
33 verbose stack wrtc: No matching version found for wrtc@^0.4.1
33 verbose stack     at pickManifest (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:101:11)
33 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:43:18
33 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
33 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
33 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
33 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
33 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:694:18)
33 verbose stack     at _drainQueueStep (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
33 verbose stack     at _drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
33 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
33 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
33 verbose stack     at processImmediate (internal/timers.js:439:21)
34 verbose cwd /Users/play/CODE/WebTorrent
35 verbose Darwin 18.6.0
36 verbose argv "/usr/local/Cellar/node/12.4.0/bin/node" "/usr/local/bin/npm" "install" "webtorrent-hybrid" "-g"
37 verbose node v12.4.0
38 verbose npm  v6.9.0
39 error code ETARGET
40 error notarget No matching version found for wrtc@^0.4.1
41 error notarget In most cases you or one of your dependencies are requesting
41 error notarget a package version that doesn't exist.
41 error notarget
41 error notarget It was specified as a dependency of 'webtorrent-hybrid'
42 verbose exit [ 1, true ]

**Comment by feross** [comment]
You're not using the official npm registry. I see you're using https://registry.npm.taobao.org. It seems that they aren't mirroring the official registry correctly.

**Comment by makelove** [comment]
yes
thank you
will try later
