### ISSUE TITLE
WebSocket connection to 'wss://tracker.btorrent.xyz/' failed: Error during WebSocket handshake: Unexpected response code: 522

### ISSUE THREAD

**Issue by RadGade** [webtorrent/webtorrent-hybrid#108]
I am trying to stream a torrent in my electron app but every time I do that it gives me this,
``WebSocket connection to 'wss://tracker.btorrent.xyz/' failed: Error during WebSocket handshake: Unexpected response code: 522`` even though I specify it to use a different tracker here ``client.add(torrentId,{announce:[`udp://tracker.torrent.eu.org:451/announce`]},..``. 

@feross I really didn't wanna open a issue but I couldn't find a place to ask questions. If you guys don't mind I have humble request that you guys open a discord server where the newbies ask for help.

**Comment by alxhotel** [comment]
Hi @RadGade,

Thanks for reporting this.

When the tracker is down, it might send that 522 error code. The issue related to adding your own trackers is already reported at webtorrent/webtorrent#1604

Also, we already have a discord server. Check it out here: https://discord.com/invite/cnXkm4Z
