### ISSUE TITLE
undefined symbol: napi_add_env_cleanup_hook

### ISSUE THREAD

**Issue by aglamazy** [webtorrent/webtorrent-hybrid#125]
**What version of this package are you using?** 4.0.3

**What operating system, Node.js, and npm version?** Ubuntu 18.04.3 LTS, Node v8.10.0, npm 3.5.2

**What happened?** Tried the example node-seed.js.
Got error: node: symbol lookup error: /usr/local/lib/node_modules/webtorrent-hybrid/node_modules/wrtc/build/Release/wrtc.node: undefined symbol: napi_add_env_cleanup_hook

**What did you expect to happen?** 
Seeding a file.

**Are you willing to submit a pull request to fix this bug?** Don't know how.

**Comment by alxhotel** [comment]
Hi @aglamazy,

Thanks for the feedback!

Please try node 12 or above.
