### ISSUE TITLE
Unable to read event under a event.

### ISSUE THREAD

**Issue by rishabhjainfinal** [webtorrent/webtorrent-hybrid#136]
**What version of this package are you using?**
latest from npm 

**What operating system, Node.js, and npm version?**
win10 , v14.16.0, 7.20.3
 
**What happened?**
unable to use the stream events inside the custom event 

## files = torrent.files;
![WhatsApp Image 2021-08-15 at 16 09 09](https://user-images.githubusercontent.com/66913499/129886528-95828192-1f01-4116-91cf-9bf1ad2e0362.jpeg)
### under the custom event, we can listen to the stream events but only sometimes, they are not stable don't show any error and most of the time they don't even fire 

**What did you expect to happen?**
listen to events even under the other custom events 

**Are you willing to submit a pull request to fix this bug?**
IDK

**Comment by DiegoRBaquero** [comment]
Seems like you have abundant logging, can you post that?

What is being skipped? Where does it freeze?

**Comment by rishabhjainfinal** [comment]
*Seems like you have abundant logging*
what do you mean by that I don't  get it - If the server request logging there is none ,
check this for my aim - https://github.com/rishabhjainfinal/some_random_projects/tree/main/TorrentDownloader

*What is being skipped? Where does it freeze?*
it just doesn't seem to listen to the events inside the custom events 
result - just end the program with no error which is because there is not an error in the application it just doesn't wait for the listening event

I think this is the issue in the dependency but we need to be sure
because today when I was testing it I got this error for the first time 
`(node:12548) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ready listeners added to [Torrent]. Use emitter.setMaxListeners() to increase limit`
