### ISSUE TITLE
Cannot import in expressjs

### ISSUE THREAD

**Issue by drakonkat** [webtorrent/webtorrent-hybrid#147]
**What version of this package are you using?**
5.0.1

**What operating system, Node.js, and npm version?**
Nodejs: 14.17.6
Npm: 6.14.15
SO: Windows 10

**What happened?**
Give me error when i change from 
`const WebTorrent = require('webtorrent');`
to 
`const WebTorrent = require('webtorrent-hybrid');`

**What did you expect to happen?**
Does not give error but works in hybrid way

Log of the error:
`Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: D:\Project\FE\webtorrent-express-api\node_modules\webtorrent-hybrid\index.js
require() of ES modules is not supported.
require() of D:\Project\FE\webtorrent-express-api\node_modules\webtorrent-hybrid\index.js from D:\Project\FE\webtorrent-express-api\routes\torrent.js is an ES module file as it is a .js file whose nearest parent package.json contain
s "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from D:\Project\FE\webtorrent-express-api\node_modules\webtorrent-hybrid\package.json.`

**Comment by DiegoRBaquero** [comment]
Latest webtorrent-hybrid is an ES module

Must be imported as such

**Comment by drakonkat** [comment]
Sorry, i didn't undestand do you exptect that is working? because i have the latest version but continue to give me the error "[ERR_REQUIRE_ESM]". Maybe i'm missing something about expressjs or something?

**Comment by Wamy-Dev** [comment]
how did you solve this?

**Comment by drakonkat** [comment]
> how did you solve this?

You can use dynamic import
