### ISSUE TITLE
WebRTC peer, not working the linux cli 

### ISSUE THREAD

**Issue by drakonkat** [webtorrent/webtorrent-hybrid#151]
**What version of this package are you using?**
5.0.2,v4.1.3

**What operating system, Node.js, and npm version?**
Linux debian/ubuntu, tried on node 14,16,latest, docker too, npm version 6,7,8

**What happened?**
Simply not working the hybrid version, so i downloaded with "npm install webtorrent-hybrid -g", tried to download/seed file but it connects only to udp source and not web source.

**What did you expect to happen?**
That it will work on every source like hybrid have to do. (I tried on windows and it simply works)

**Are you willing to submit a pull request to fix this bug?**
I can try to help, i can give access to my test VPS for test and make some active test with no problem. But i cannot undestand the problem.

I suppose it's because is a VPS and has problem with the "WRTC" unfortunatly i cannot find log or hint about the error, because everything seems to work on the cli. If there is some suggestion on what i can check.

**Comment by DiegoRBaquero** [comment]
Do you control the WebRTC peer? Are you downloading or uploading in the VPS?

**Comment by drakonkat** [comment]
I have tried both, uploading and downloading. With normal upd user works otherwhise no

**Comment by drakonkat** [comment]
I don't know how to figure it out, if you want i can open a nodejs container on docker, and give access to the cli (I can send you credential on discord) and the list of the command that i have runned

**Comment by DiegoRBaquero** [comment]
It's probably related to the wrtc package. That's why there are a bunch of similar issues :(

Please enable debug logs by doing `DEBUG=* webtorrent-hybrid ...` and see if there anything telling in the logs

**Comment by drakonkat** [comment]
Yes i have attached the log, now i see some error i will try to investigate too
[log_seed_file.log](https://github.com/webtorrent/webtorrent-hybrid/files/7980046/log_seed_file.log)

**Comment by drakonkat** [comment]
Is there a way i can help? i'm trying to figureout the problem... i suppose is the wrtc dependencies which is no longer supported a lot. And i'm trying to rebuild it direct in a docker image to understand if i can make it work

**Comment by drakonkat** [comment]
Ok i find out something, if i take ufw on a clean ubuntu install, and launch 
`ufw default allow incoming`
the webtorrent-hybrid-cli start working, it works in docker and in a normal VPS (I made some test)

So probably to work the web peer need to have some port opened but i don't know which port (It's not optimal keep every port opened (I tried 8080,80,443,3000,8000,8888,9000,51413,9876 but no one resolved my problem) 

@DiegoRBaquero do you know which port is used exactly in incoming way? (I suppose fail the request of the metadata from the web peer)
