### ISSUE TITLE
Destop client stop working both down and up

### ISSUE THREAD

**Issue by myotavietnam** [webtorrent/webtorrent-hybrid#70]
Iam having problem these days for the destop window verson

I can not download any file ( from webtorrent client with webtorrent client ) 
The case as below :
+OS : Window 7 64 bit.
+Client 1 : Creat torrent and seed 
+Client 2 : Download from magnet link of client (1) , the client 2 just alway just show " Loading torrent"

http://farm5.staticflickr.com/4375/36619669551_10363f498e_b.jpg

+CHange client 2 to be seeder and client 1 to be downloader , same case .
+All files face same problem .
+2 client with diffirent Internet line from 2 suppliers 

Pls could you advise what problem could be ?

**Comment by DiegoRBaquero** [comment]
Must be a firewall/networking issue where the two peers can't connect to each other.

**Comment by myotavietnam** [comment]
I have uninstalled all ativirus solfware and also disable the window firewall , the case was unsolved .
before I use regularly , no such problem . This case just happen in recent 7-10 days.
Try https://btorrent.xyz/  , like this : 
blob:https://www.flickr.com/4aa70adc-54e3-4c8c-b6d5-a91550718aae

I have tried many pc with diffirent internet line , same problem .

Is is possible any harmful bug ?
