### ISSUE TITLE
How to seed multiple files under multiple magnet link

### ISSUE THREAD

**Issue by teddybugs** [webtorrent/webtorrent-hybrid#73]
Hello,

Im using:
**npm install webtorrent-hybrid -g**

```
webtorrent-hybrid -v
1.11.0 (0.98.20)
```

i have a folder at : /var/www/html/mp4/ with 100 mp4 files inside it, they are named in sequence:
1.mp4
2.mp4
3.mp4
..
until
100.mp4

how do i seed all of these files 1 by 1 with each of them have different magnet link or torrent?

**Comment by Ciao121** [comment]
I think "seed /var/www/html/mp4/*" should work.

**Comment by teddybugs** [comment]
tried, it did show magnet link for each file, but the videos do not download on browser, it work only for single file when you seed using:

`webtorrent-hybrid seed /var/www/html/mp4/ 1.mp4 --keep-seeind`

but that will only work for one file. maybe need a custom bash script to loop and run the command? no way to get webtorrent-hybrid to seed all?

**Comment by Ciao121** [comment]
For me it wors. Are you trying from instant.io?
Maybe the seeder just stop seending as here: https://github.com/webtorrent/webtorrent-hybrid/issues/67
Try to download the second or third file as first.

**Comment by teddybugs** [comment]
For me it works. Are you trying from instant.io?
#no, i use webtorrent.min.js

**Comment by Ciao121** [comment]
Try from instant.io so you can check if it's a client or a server problem.

**Comment by teddybugs** [comment]
not working using instant.io,

**Comment by Ciao121** [comment]
You are right! Sorry. I just remembered that made some script.
The command is webtorrent-hybrid seed path/to/file1 path/to/file2

**Comment by feross** [comment]
It's not possible to debug this issue without additional information. If this is still an issue, please leave a comment or open a new issue.
