### ISSUE TITLE
Question : Is there an alternative to electron-webrtc ? 

### ISSUE THREAD

**Issue by Fabiencdp** [webtorrent/webtorrent-hybrid#74]
Hey ! It's more a question than an issue. 
I wonder if you plan to change the dependencies to electron by another package or if you know a better alternative to dig in ? 
Great work by the way !

**Comment by DiegoRBaquero** [comment]
Maybe headless chrome, puppeteer, could be an option, not built however.

**Comment by feross** [comment]
`wrtc` is another alternative. See https://github.com/webtorrent/webtorrent-hybrid/issues/76
