### ISSUE TITLE
seed command very slow

### ISSUE THREAD

**Issue by zarzen** [webtorrent/webtorrent-hybrid#78]
Seeding speed is very slow, and often broken. While using `webtorrent-desktop` works well under the same network situation.
Tested on Linux and Mac OSX.

**Comment by feross** [comment]
This is due to how `webtorrent-hybrid` is built at the moment, using `electron-webrtc`. We're considering moving to `wrtc` which may alleviate this issue. You can follow that issue here: https://github.com/webtorrent/webtorrent-hybrid/issues/76
