### ISSUE TITLE
Excessive memory usage

### ISSUE THREAD

**Issue by bounteous** [webtorrent/webtorrent-hybrid#85]
Hi, I am using webtorrent-hybrid Node JS v8 from Linux (Gentoo), I have a directory with 80 songs in mp3 format, each file does not exceed the 5 minute time. For each song that is added to the library to be shared increases the use of RAM, using 5gb to share my music directory.

This is my code, some solution?
https://github.com/bounteous/musicmonkey-api/blob/master/seed/functions.library.js

**Comment by alxhotel** [comment]
I believe this issue is related to this one webtorrent/webtorrent#1026
