### ISSUE TITLE
npm installation error

### ISSUE THREAD

**Issue by lijy1992** [webtorrent/webtorrent-hybrid#94]
I ran into a problem installing webtorrent-hybrid:

> root@acgwang:/# npm install webtorrent-hybrid -g
> npm ERR! Linux 4.15.0-46-generic
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "webtorrent-hybrid" "-g"
> npm ERR! node v8.10.0
> npm ERR! npm  v3.5.2
> npm ERR! path /usr/local/lib/node_modules/webtorrent-hybrid/node_modules/ascli
> npm ERR! code ENOENT
> npm ERR! errno -2
> npm ERR! syscall stat
> 
> npm ERR! enoent ENOENT: no such file or directory, stat '/usr/local/lib/node_modules/webtorrent-hybrid/node_modules/ascli'
> npm ERR! enoent ENOENT: no such file or directory, stat '/usr/local/lib/node_modules/webtorrent-hybrid/node_modules/ascli'
> npm ERR! enoent This is most likely not a problem with npm itself
> npm ERR! enoent and is related to npm not being able to find a file.
> npm ERR! enoent 
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /npm-debug.log

Here is the version information:

os:
ubuntu18.04 LTS
node:8.10.0
npm:5.3.2

**Comment by l-san** [comment]
Try this:
`sudo yarn global add webtorrent-hybrid`

**Comment by feross** [comment]
It's not possible to debug this issue without additional information. Can you try again but first install Node.js v10? If this is still an issue, please leave a comment or open a new issue.
