### ISSUE TITLE
is there a way to make this usable on blocked wifi's ?  

### ISSUE THREAD

**Issue by toltarisa** [webtorrent/webtorrent-hybrid#96]
When i run the command, it's not giving  response from server.it's just hanging at fetching torrent metadata.

**Comment by DiegoRBaquero** [comment]
I'm a bit lost, you are not getting response from which server? If bittorrent is blocked in your network there's nothing we can do.

**Comment by toltarisa** [comment]
Yeah utorrent is blocked on my network.I was just tried peerflix while ago but it wasn't working properly.I thougth maybe there is a solution on this project.But thanks anyway

**Comment by DiegoRBaquero** [comment]
Alright, sorry it wouldn't work for you
